# Generated by Django 5.1.7 on 2025-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_customuser_email_token_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('active', models.BooleanField(default=True, verbose_name='Abonnement actif')),
            ],
        ),
    ]
